export const FETCH_CATALOGS = 'FETCH_CATALOGS';
export const FETCH_CATALOGS_REQUEST = 'FETCH_CATALOGS_REQUEST';
export const FETCH_CATALOGS_FAILURE = 'FETCH_CATALOGS_FAILURE';

export const FETCH_SUBCATALOGS = 'FETCH_SUBCATALOGS';
export const FETCH_SUBCATALOGS_REQUEST = 'FETCH_SUBCATALOGS_REQUEST';
export const FETCH_SUBCATALOGS_FAILURE = 'FETCH_SUBCATALOGS_FAILURE';

export const ADD_CATALOG = 'ADD_CATALOG';
export const ADD_SUBCATALOG = 'ADD_SUBCATALOG';
export const DELETE_CATALOG = 'DELETE_CATALOG';
export const DELETE_SUBCATALOG = 'DELETE_SUBCATALOG';