export const SEND_CONTACT_FORM = 'SEND_CONTACT_FORM';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_FAILURE = 'FORM_SUBMIT_FAILURE';
export const FORM_SUBMIT_CLOSE = 'FORM_SUBMIT_CLOSE';