export const SET_ACTIVE_CURRENCY = "SET_ACTIVE_CURRENCY";
export const FETCH_CURRENCY_RATE = "FETCH_CURRENCY_RATE";
export const SET_ACTIVE_CURRENCY_AND_RATE = "SET_ACTIVE_CURRENCY_AND_RATE";
export const FETCH_CURRENCY_RATE_ERROR = "FETCH_CURRENCY_RATE_ERROR";
