export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FORM_CLOSE = 'SEND_ORDER_FORM_CLOSE';
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE';